apiVersion: v1
kind: Secret
metadata:
  name: sales-intelligence-platform-secrets
  namespace: default
  labels:
    app: sales-intelligence-platform
    component: secrets
    environment: ${ENV}
    managed-by: terraform
  annotations:
    secret.kubernetes.io/managed-by: terraform
    secret.kubernetes.io/last-rotation: ${TIMESTAMP}
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'sales-intelligence'
    vault.hashicorp.com/secret-volume-path: '/vault/secrets'
    encryption.kubernetes.io/encrypted: 'true'
    reloader.stakater.com/match: 'true'

type: Opaque

stringData:
  # Authentication & Security
  JWT_SECRET: ${JWT_SECRET}  # Min 32 chars, high entropy secret for JWT signing
  ENCRYPTION_KEY: ${ENCRYPTION_KEY}  # 64-char AES-256 key for data encryption

  # Database Credentials
  DB_PASSWORD: ${DB_PASSWORD}  # PostgreSQL database password
  REDIS_PASSWORD: ${REDIS_PASSWORD}  # Redis cache password

  # LinkedIn API Credentials
  LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}  # OAuth2 client ID for LinkedIn Ads API
  LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}  # OAuth2 client secret for LinkedIn Ads API

  # Google Ads API Credentials  
  GOOGLE_ADS_CLIENT_ID: ${GOOGLE_ADS_CLIENT_ID}  # OAuth2 client ID for Google Ads API
  GOOGLE_ADS_CLIENT_SECRET: ${GOOGLE_ADS_CLIENT_SECRET}  # OAuth2 client secret for Google Ads API

  # AI/ML Service Credentials
  OPENAI_API_KEY: ${OPENAI_API_KEY}  # OpenAI API key for GPT models

  # TLS Certificates (Base64 encoded)
  TLS_CERT: ${TLS_CERT}  # TLS certificate for secure communication
  TLS_KEY: ${TLS_KEY}  # TLS private key

  # Monitoring & Observability
  JAEGER_AGENT_PASSWORD: ${JAEGER_AGENT_PASSWORD}  # Jaeger tracing agent password
  ALERT_WEBHOOK_SECRET: ${ALERT_WEBHOOK_SECRET}  # Alerting webhook authentication

  # Service Account Tokens
  SERVICE_ACCOUNT_TOKEN: ${SERVICE_ACCOUNT_TOKEN}  # K8s service account token

  # Additional Security Keys
  COOKIE_SECRET: ${COOKIE_SECRET}  # Session cookie encryption key
  CSRF_TOKEN_SECRET: ${CSRF_TOKEN_SECRET}  # CSRF token generation secret

  # Backup & Recovery
  BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}  # Key for encrypting backups

  # API Rate Limiting
  RATE_LIMIT_SECRET: ${RATE_LIMIT_SECRET}  # Secret for rate limit token generation

  # Audit Logging
  AUDIT_SIGNING_KEY: ${AUDIT_SIGNING_KEY}  # Key for signing audit logs

  # Feature Flag Management
  FEATURE_FLAG_API_KEY: ${FEATURE_FLAG_API_KEY}  # API key for feature flag service