apiVersion: 1

datasources:
  # Prometheus datasource configuration for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      # Match Prometheus scrape interval from prometheus.yml
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: POST
      # Enable exemplar support for trace correlation
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
    secureJsonData:
      httpHeaderValue1: "Bearer ${PROMETHEUS_API_TOKEN}"

  # Elasticsearch datasource configuration for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[sales-intelligence-logs-]YYYY.MM.DD"
    version: 1
    editable: true
    jsonData:
      esVersion: "7.17.0"
      timeField: "@timestamp"
      interval: "Daily"
      logMessageField: "message"
      logLevelField: "level"
      # Optimize query performance based on ES config
      maxConcurrentShardRequests: 5
      timeInterval: "10s"
    secureJsonData:
      basicAuth: true
      basicAuthPassword: "${ELASTICSEARCH_PASSWORD}"